
create table if not exists users
(
    id  long AUTO_INCREMENT NOT NULL,
    login    varchar(500),
    name     varchar(50),
    email    varchar(50),
    birthday date,
        CONSTRAINT pk_users PRIMARY KEY (id)
);

create table if not exists not_mutual_friends
(
    friendship_id long generated by default as identity primary key,
    user_id       long REFERENCES users (id),
    friend_id     long

);

create table if not exists mutual_friends
(
    friendship_id long generated by default as identity primary key,
    user_id       long REFERENCES users (id),
    friend_id     long

);

create table if not exists rating
(
    rating_id int primary key,
    rating_name  character varying(500)
);

create table if not exists films
(
    id      long AUTO_INCREMENT NOT NULL,
    name         varchar(50)         not null,
    description  varchar(500),
    release_date timestamp,
    duration     int,
    mpa       int REFERENCES rating (rating_id),
    CONSTRAINT pk_films PRIMARY KEY (id)
);

create table if not exists film_likes
(
    likeness_id long generated by default as identity primary key,
    user_id long REFERENCES users (id),
    film_id long REFERENCES films (id)
);

create table if not exists genres
(
    id int primary key,
    genre_name varchar(50)
);

create table if not exists film_genre
(
    id int primary key REFERENCES genres (id),
    film_id long REFERENCES films (id)

    );

