
create table if not exists users
(
    user_id  long generated by default as identity primary key,
    login    varchar(50) not null,
    name     varchar(50),
    birthday timestamp
);

create table if not exists not_mutual_friends
(
    friendship_id long generated by default as identity primary key,
    user_id       long REFERENCES users (user_id) not null,
    friend_id     long not null
);

create table if not exists mutual_friends
(
    friendship_id long generated by default as identity primary key,
    user_id       long REFERENCES users (user_id) not null,
    friend_id     long not null
);


create table if not exists rating
(
    rating_id int generated by default as identity primary key,
    rating_name character varying(500) not null
);

create table if not exists films
(
    film_id  long generated by default as identity primary key,
    name    varchar(50) not null,
    description varchar(500),
    release_date timestamp,
    duration int,
    rating int REFERENCES rating (rating_id)
 );
create table if not exists film_likes
(
    likeness_id long generated by default as identity primary key,
    user_id long REFERENCES users (user_id),
    film_id long REFERENCES films (film_id)
);


create table if not exists film_genre
(
    genre_id int generated by default as identity primary key,
    film_id long REFERENCES films (film_id) not null
);

create table if not exists genres
(
    genre_id int generated by default as identity primary key,
    genre_name varchar(50)
);

